# Site settings
name: Stephan Akkerman
title: Stephan Akkerman | Back End Software Engineer
description: Back-end software engineer focused on machine learning and trading
url: https://stephanakkerman.github.io/
baseurl: ''
email: stephan.akkerman@gmail.com
cover: https://stephanakkerman.github.io/img/og.png
logo: https://stephanakkerman.github.io/img/emojis/technologist.png
resume: https://stephanakkerman.github.io/resume.pdf
social:
  - title: email
    url: mailto:stephan.akkerman@gmail.com
  - title: instagram
    url: https://instagram.com/StephanAkkerman
  - title: github
    url: https://github.com/StephanAkkerman
  - title: linkedin
    url: https://www.linkedin.com/in/StephanAkkerman

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
